; Inno Setup script for Wavetype. Build with packaging/build.ps1 (it runs PyInstaller first).
; Per-user install: no admin prompt, files in %LOCALAPPDATA%\Programs\Wavetype.
; User data (key, vocab, recordings, logs) lives in %APPDATA%\Wavetype and %LOCALAPPDATA%\Wavetype
; (see paths.py) and survives upgrades; the uninstaller asks before removing it.

#ifndef AppVersion
  #define AppVersion "0.1.0"
#endif
#define AppName "Wavetype"
#define AppExe "Wavetype.exe"

[Setup]
AppId={{5B7E2C1A-8F4D-4C3B-9A6E-2D1F0B7C9E41}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher=Lorenzo Montes
AppPublisherURL=https://github.com/LorenzoAlejandroMontes/wavetype
AppSupportURL=https://github.com/LorenzoAlejandroMontes/wavetype/issues
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DisableDirPage=yes
DisableReadyPage=yes
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
OutputDir=..\dist
OutputBaseFilename=Wavetype-Setup-{#AppVersion}
SetupIconFile=..\assets\wavetype.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern dynamic
; artwork generated by packaging/make_icon.py (build.ps1 runs it), several sizes for DPI scaling
WizardSmallImageFile=art\small-55.bmp,art\small-64.bmp,art\small-83.bmp,art\small-92.bmp,art\small-110.bmp,art\small-119.bmp,art\small-138.bmp
WizardSmallImageFileDynamicDark=art\small-55.bmp,art\small-64.bmp,art\small-83.bmp,art\small-92.bmp,art\small-110.bmp,art\small-119.bmp,art\small-138.bmp
WizardImageFile=art\large-164.bmp,art\large-192.bmp,art\large-246.bmp,art\large-273.bmp,art\large-328.bmp,art\large-355.bmp,art\large-410.bmp
WizardImageFileDynamicDark=art\large-164.bmp,art\large-192.bmp,art\large-246.bmp,art\large-273.bmp,art\large-328.bmp,art\large-355.bmp,art\large-410.bmp
CloseApplications=force
RestartApplications=no
VersionInfoVersion={#AppVersion}
VersionInfoDescription={#AppName} Setup

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
english.StartupTask=Start Wavetype when I sign in to Windows
english.DesktopTask=Add a desktop shortcut
english.LaunchNow=Launch Wavetype
english.RemoveData=Also remove your Wavetype key, dictionary, history and recordings from this PC?%n%nChoose No to keep them for a future install.

[Tasks]
Name: "startup"; Description: "{cm:StartupTask}"
Name: "desktopicon"; Description: "{cm:DesktopTask}"; Flags: unchecked

[Files]
; everything PyInstaller put in dist\Wavetype (the spec lists its inputs one by one: no user data)
Source: "..\dist\Wavetype\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#AppName}"; Filename: "{app}\{#AppExe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExe}"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; \
  ValueName: "{#AppName}"; ValueData: """{app}\{#AppExe}"""; Flags: uninsdeletevalue; Tasks: startup

[Run]
Filename: "{app}\{#AppExe}"; Description: "{cm:LaunchNow}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
; a running Wavetype holds its files open: stop it before removing them
Filename: "{sys}\taskkill.exe"; Parameters: "/f /im {#AppExe}"; Flags: runhidden; RunOnceId: "StopWavetype"

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Code]
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
  begin
    { silent uninstall keeps the data (default button = No) }
    if SuppressibleMsgBox(CustomMessage('RemoveData'), mbConfirmation, MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES then
    begin
      DelTree(ExpandConstant('{userappdata}\Wavetype'), True, True, True);
      DelTree(ExpandConstant('{localappdata}\Wavetype'), True, True, True);
    end;
  end;
end;
